version: '3' 
services:

  ros-base:
    image: ros-base:user
    user: $CURRENT_UID
    working_dir: $HOME
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    stop_grace_period: 1s
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null

  gazebo:
    image: gazebo:latest
    depends_on:
      - ros-base
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - $HOME/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/src/sim_device:/root/catkin_ws/src/sim_device
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null

  moveit :
    image: moveit:latest
    depends_on:
    - ros-base
    - gazebo
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
     # ROS_IP: localhost
     # ROS_MASTER_URI: "http://localhost:11311"
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - $HOME/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/src/sim_device:/root/catkin_ws/src/sim_device
      - $HOME/src/sim_device/thesis_moveit_config/config/moveit.rviz:/root/.rviz/default.rviz
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    command: tail -f /dev/null
  
  pcl:
    image: pcl:latest
    depends_on:
      - ros-base
      - gazebo
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - $HOME/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/src/v4r:/root/v4r                                         
      - $HOME/src/ros_pcl:/root/catkin_ws/src/ros_pcl
    privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null


  pythonocc:
    image: pythonocc:latest
    depends_on:
        - moveit
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
      # in order to run python3 from conda
      PATH: '/root/miniconda/envs/pythonocc/bin:$PATH'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /usr/share/fonts/:/usr/share/fonts
      - /home/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/src/rel_pose_ext:/root/catkin_ws/src/rel_pose_ext
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    command: tail -f /dev/null
