ARG DOCKER_BASE_IMAGE=ubuntu:18.04
FROM ${DOCKER_BASE_IMAGE}

ENV DEBIAN_FRONTEND noninteractive
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get clean && \
    apt-get update && apt-get -y install \
    htop \
    build-essential \
    apt-utils \    
    ssh \
    git \
    vim \
    software-properties-common \
    apt-transport-https \
    ca-certificates \
    wget \
    curl \
    openssh-server \
    xorg && \
    rm -rf /var/lib/apt/list/*